# Welcome To numpy

Import numpy library as shown below

In [1]:
import numpy as np

This way we can make numpy array

In [2]:
myarr = np.array([1,2,3,4])


In [3]:
myarr

array([1, 2, 3, 4])

If we want to mention how any bits interger we want to use in array then see below example we will be using 8 bit integer

In [4]:
myarr1 = np.array([1,2,3,4],np.int8)

In [5]:
myarr1

array([1, 2, 3, 4], dtype=int8)

If we use number exceeding 8 bits then we get another incorrect number format

In [6]:
myarr2 = np.array([1,2,333333,4],np.int8)

In [7]:
myarr2

array([ 1,  2, 21,  4], dtype=int8)

In [8]:
myarr2[1]


2

If want to know dimension of array then we use following, it gave (4,) represnting 1 dimension array with 4 columns

In [9]:
myarr2.shape

(4,)

If want to know datatype of array,use dtype

In [10]:
myarr.dtype

dtype('int32')

We have made array in 2-D as shown

In [11]:
myarr3 = np.array([[1,2,3,4]])

In [12]:
myarr3


array([[1, 2, 3, 4]])

In [13]:
myarr3.shape

(1, 4)

Accessing element from 2-d array

In [14]:
myarr3[0,2]

3

# Array Creation: Conversion from other Python structures

In [15]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.dtype

dtype('int32')

In [19]:
listarray.size

9

In [20]:
np.array({20,12,30,30})

array({20, 12, 30}, dtype=object)

Below code give the array of 2-d with 2 rows and 5 columns with 0 values

In [21]:
zeros = np.zeros((2,5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Below code gives array of range from 1 to 15-1

In [23]:
rn = np.arange(15)

In [24]:
rn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Below code gives an array which has equal linear spacing starting from 1 and ending at 50 given 10 elements including them

In [25]:
lspace = np.linspace(1,50,10)

In [26]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

Below code gives you an empty array of 2-d with 4 rows and 6 columns with any random values in it

In [27]:
emp = np.empty((4,6))

In [28]:
emp

array([[2.31650014e-152, 1.69288051e+190, 6.01347002e-154,
        1.46921998e+195, 9.82395831e+252, 5.63782432e+247],
       [7.20100785e+252, 2.45650349e+198, 6.66424029e+217,
        1.68821038e+195, 3.15099219e+156, 3.17095867e+180],
       [6.01347002e-154, 1.45913207e-152, 8.70860497e+183,
        2.59441389e+161, 4.23974316e+175, 2.64521686e+185],
       [3.77704682e+233, 1.86927589e-152, 1.94623474e+227,
        6.01347002e-154, 2.38954692e+180, 9.82158065e+252]])

In [29]:
myarr4 = np.array([1,2,3,4])

In [30]:
emp_like = np.empty_like(myarr4)

In [31]:
emp_like


array([1074359968,        533,          0,          0])

Below code makes an identity matrix of given dimension in parameter here 10 x 10

In [32]:
ide = np.identity(10)

In [33]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
myarr5 = np.arange(99)

In [35]:
myarr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

If we want to reshape above array then we can do code written below, here we are using reshape element and parameter shouldbe such that multiplication of both should give size of array otherwise it will not reshape and will give error. In this case size of array is 99 and parameters is 3 and 33 so 3*33=99 satisfies

In [36]:
myarr5.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

If we want it in original form again then use below code

In [37]:
myarr5.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

Below code adds up each elements in particular columns and makes array of final result of all column here 1+4+7=12, 2+5+8=15 and 3+6+9=18

In [39]:
x.sum(axis=0)

array([12, 15, 18])

Below code adds up each elements in particular rows and makes array of final result of all row here 1+2+3=6, 4+5+6=15 and 7+8+9=24

In [40]:
x.sum(axis=1)

array([ 6, 15, 24])

In [41]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Below code gives transpose of array

In [42]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
x.ndim

2

In [44]:
for item in x.flat:
 print(item)

1
2
3
4
5
6
7
8
9


It gives no of dimensions of array

In [45]:
x.ndim

2

Below code gives us total number of bytes used in array

In [46]:
x.nbytes

36

In [47]:
x[0].nbytes

12

In [48]:
x[0][0].nbytes

4

In [49]:
myarr6 = np.array([1,4,2,7])

Below code returns index of maximum element from array as result

In [50]:
myarr6.argmax()

3

Below code returns index of minimum element from array as result

In [51]:
myarr6.argmin()

0

Below code return array of index according to sorted values present in indexes

In [52]:
myarr6.argsort()

array([0, 2, 1, 3], dtype=int64)

In [53]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
x.argmax()

8

In [55]:
x.argmin()

0

In [56]:
x.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [57]:
x.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [58]:
x.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [59]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [60]:
x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [61]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x1 = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

Below code is addition matrix

In [63]:
x+x1

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

Below code is matrix multiplication

In [64]:
x*x1

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

Below code gives square root of every element of array

In [65]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [66]:
x.sum()

45

In [67]:
x.max()

9

In [68]:
x.min()

1

In [69]:
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

first array elements below represent x  and second array element represent y then element is arr[x][y]

In [70]:
np.where(x<5)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [71]:
type(np.where(x<5))

tuple

In [72]:
np.count_nonzero(x)

9

In [73]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [74]:
import sys

In [75]:
py_ar = [1,3,5,7]

In [76]:
np_ar = np.array(py_ar)

In [77]:
sys.getsizeof(py_ar[0])*len(py_ar)

112

In [78]:
np_ar.itemsize*np_ar.size

16

So above thing proves how numpy saves space very much than that of normal list of python